inputSet:
  identifier: prod_input_set
  name: Production Environment Input Set
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: saas_factory_eks_deployment
    variables:
      - name: ENV
        type: String
        value: production
      - name: AWS_REGION
        type: String
        value: us-east-1
      - name: CLUSTER_NAME
        type: String
        value: saas-factory-prod-cluster
      - name: ACCOUNT_ID
        type: String
        value: "<+account.complianceStatus>"