inputSet:
  identifier: prod_input_set
  name: Production Environment Input Set
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: saas_factory_eks_deployment
    variables:
      - name: ENV
        type: String
        value: production
      - name: AWS_REGION
        type: String
        value: us-east-1
      - name: CLUSTER_NAME
        type: String
        value: saas-factory-prod-cluster
      - name: ACCOUNT_ID
        type: String
        value: <+secrets.getValue("aws_account_id")>
      - name: EMAIL
        type: String
        value: smashkat12@gmail.com
      - name: DOMAIN
        type: String
        value: thinkm8.co.uk
      - name: HOSTED_ZONE_ID
        type: String
        value: Z0494651P0BXWLJV1MEX